### ISSUE TITLE
Puzzle Image Resolution

### ISSUE THREAD

**Issue by ghost** [PGSSoft/PuzzleMaker#2]
Hi,
Firstly this is a great component and I am currently using it in an app I am developing.

I have one question regarding how the puzzle is generated however.

When I log the image.scale in the PuzzleMaker it doesn't seem to recognise the @2x when rendering the puzzle pieces.  

Is their way when generating the puzzle to ensure that it displays retina images when needed?

Hope to hear from you soon :)

**Comment by ghost** [comment]
Hi,

After some diggin the issue was with me loading images from urls.

As such the issue was with my code not yours!

**Comment by pwlkania** [comment]
Hi,

Glad you like it and it's working as expected :-)

I'm closing this issue.
